#!/bin/bash
# CMU.ADV

# flags to be sent directly to the compiler
FLAGS=""

# tell the compiler to print a bunch of nonsense
VERBOSE="-v -w1"

# optional debug flag
DEBUG="-d"

# flags shared between web and cmd builds
MAKE_FLAGS="
-DLANGUAGE=en_us
-DMESSAGESTYLE=neu
-nobanner
-Fs ../../src/"

# filename for chararray makefile
MAKE_CMD="obj/cmd/cmu_adv_cmd.t3m"

# filename for web makefile
MAKE_WEB="obj/web/cmu_adv_web.t3m"

# flags for building to the command line
CMD_FLAGS="
-Fy ../cmd -Fo ../cmd
-I ../../src/
-o ../../tgt/cmu_adv_cmd.t3
-lib system
-lib adv3/adv3"


# flags for building to the web
WEB_FLAGS="
-D TADS_INCLUDE_NET
-Fy ../web -Fo ../web
-I ../../src/
-o ../../tgt/cmu_adv_web.t3
-lib system
-lib adv3/adv3web
-lib webui
-source tadsnet"


function usage {
  echo "usage: . build [-cdhrw]"
}


# help
#
# When the user does something dumb, display this help text.
function help {
  usage
  echo "options:
    -b, --build    clean both targets, compile and run
    -c, --clean    clean build files without compiling
    -d, --debug    send debug flags to the compiler
    -h, --help     displays usage and help text
    -r, --run      runs the console build
    -w, --web      runs the web build"
}


# make
#
# Constructs two `*.t3m` files for building the t3make.
function make {
  echo -e "${MAKE_FLAGS}" > $MAKE_WEB
  echo -e "${MAKE_FLAGS}" > $MAKE_CMD

  for dir in $(find ./src/ -type d); do
    echo "-Fs ../../src/`basename ${dir}`" >> $MAKE_WEB
    echo "-Fs ../../src/`basename ${dir}`" >> $MAKE_CMD
  done

  echo "${WEB_FLAGS}" >> $MAKE_WEB
  echo "${CMD_FLAGS}" >> $MAKE_CMD

  for file in $(find ./src -name '*.t'); do
    echo "-source ${file##*/}" >> $MAKE_WEB
    echo "-source ${file##*/}" >> $MAKE_CMD
  done
}


# clean
#
# Explicitly deletes all the object files in `obj/` and deletes
# the `*.t3` executables from `tgt/`.
function clean {
  t3make -clean -f $MAKE_WEB
  t3make -clean -f $MAKE_CMD
}


# build
#
# When the `-b` is explicitly specified, it first calls `clean`
# and then this function, which first constructs the `*.t3m`
# makefiles, compiles the project, and then runs it.
function build {
  make
  t3make $FLAGS -f $MAKE_WEB &&
  t3make $FLAGS -f $MAKE_CMD
}


# debug
#
# sets flags for a debug build
function debug {
  FLAGS="$DEBUG $VERBOSE $FLAGS"
  build
  run
}


# run
#
# Uses frob to run the command line version.
function run {
  frob tgt/cmu_adv_cmd.t3
}


# web
#
# Uses frob to run the web build.
function web {
  frob -N 44 tgt/cmu_adv_web.t3
}


if [ $# -gt 0 ]; then
while [ "$1" != "" ]; do
  case $1 in
    -b | --build )  clean
                    build
                    run;;
    -d | --debug )  debug;;
    -c | --clean )  clean;;
    -h | --help  )  help;;
    -r | --run   )  run;;
    -w | --web   )  web;;
    *            )  usage;;
  esac
  shift
done
else
  build && run
fi

