#!/bin/bash
# cmu-adv


# flags shared between web and cmd builds
FLAGS="
-DLANGUAGE=en_us
-DMESSAGESTYLE=neu"


# flags for building to the command line
CMD_FLAGS="
-nobanner
-Fy cmd -Fo cmd
-I ../src/
-Fs ../src/ -Fs ../src/people/ -Fs ../src/map/
-o ../tgt/cmu_adv_cmd.t3
-lib system
-lib adv3/adv3"


# flags for building to the web
WEB_FLAGS="
-nobanner
-D TADS_INCLUDE_NET
-Fy web -Fo web
-I ../src/
-Fs ../src/ -Fs ../src/people/ -Fs ../src/map/
-o ../tgt/cmu_adv_web.t3
-lib system
-lib adv3/adv3web
-lib webui
-source tadsnet"


# a list of files to compile
SOURCE_FILES="
# sources
-source main

-source about
-source hints
-source init
-source items
-source user

# people
-source people

-source 251_ta
-source bescott
-source interviewer
-source officer

# map
-source map

-source baker
-source campus
-source cfa
-source doherty
-source ghc
-source hammerschlag
-source warner

# utilities
-source util

-source combat
-source dijkstra"


function usage {
  echo "usage: .cmu-adv [-chrw]"
}


# help
#
# When the user does something dumb, display this help text.
function help {
  usage
  echo "options:
    -b, --build    clean both targets, compile and run
    -c, --clean    clean build files without compiling
    -h, --help     displays usage and help text
    -r, --run      runs the console build
    -w, --web      runs the web build"
}


# make
#
# Constructs two `*.t3m` files for building the t3make.
function make {
  echo "${FLAGS}" > 'obj/cmu_adv_cmd.t3m'
  echo "${CMD_FLAGS}" >> 'obj/cmu_adv_cmd.t3m'
  echo "${SOURCE_FILES}" >> 'obj/cmu_adv_cmd.t3m'

  echo "${FLAGS}" > 'obj/cmu_adv_web.t3m'
  echo "${WEB_FLAGS}" >> 'obj/cmu_adv_web.t3m'
  echo "${SOURCE_FILES}" >> 'obj/cmu_adv_web.t3m'
}


# clean
#
# Explicitly deletes all the object files in `obj/` and deletes
# the `*.t3` executables from `tgt/`.
function clean {
  t3make -clean -f obj/cmu_adv_cmd.t3m
  t3make -clean -f obj/cmu_adv_web.t3m
}


# build
#
# When the `-b` is explicitly specified, it first calls `clean`
# and then this function, which first constructs the `*.t3m`
# makefiles, compiles the project, and then runs it.
function build {
  make
  t3make -v -w1 -f obj/cmu_adv_web.t3m &&
  t3make -v -w1 -f obj/cmu_adv_cmd.t3m
}


# run
#
# Uses frob to run the command line version.
function run {
  frob tgt/cmu_adv_cmd.t3
}


# web
#
# Uses frob to run the web build.
function web {
  frob -N 44 tgt/cmu_adv_web.t3
}

if [ $# -gt 0 ]; then
while [ "$1" != "" ]; do
  case $1 in
    -b | --build )  clean
                    build
                    run;;
    -c | --clean )  clean;;
    -h | --help  )  help;;
    -r | --run   )  run;;
    -w | --web   )  web;;
    *            )  usage;;
  esac
  shift
done
else
  build && run
fi

